### ISSUE TITLE
Probing shouldn't be implementation specific

### ISSUE THREAD

**Issue by dprotaso** [knative-extensions/net-gateway-api#663]
We need a general way of solving this that isn't specific to an implementation. Currently we are looking at the port strings on the endpoints

eg. maybe in this code we need to look at the K8s Service and not the endpoint

_Originally posted by @dprotaso in https://github.com/knative-extensions/net-gateway-api/pull/658#pullrequestreview-1971397750_

**Comment by lexfrei** [comment]
This still blocks a fully spec-conformant Gateway implementation today.

I maintain a Gateway API controller whose data plane is a Cloudflare Tunnel (cloudflared, outbound-only): there is no in-cluster L7 Service to dial, and the Gateway advertises a `Hostname`-type `status.address` (the tunnel CNAME) — a valid `AddressType` per the spec. With Knative Serving + net-gateway-api pointed at it the route is fully programmed and serves traffic through the edge, yet every revision is stuck `Uninitialized`, because the readiness probe is dialed directly at the data plane (`status.addresses[0]` on :80/:443 in the no-Service case) and a tunnel CNAME doesn't resolve in-cluster.

To be precise about the spec: I'm not arguing "just trust `Programmed`." It's defined as config "assumed to be ready soon," not "serving now," so I understand why net-gateway-api wants positive end-to-end confirmation before shifting traffic — Gateway API genuinely has no "this config is serving" signal. The narrower problem is that the probe hard-assumes the data plane is a set of directly-probeable in-cluster HTTP endpoints. That topology isn't something the Gateway API contract requires an implementation to provide, so the probe excludes conformant implementations whose data plane is off-cluster / tunnel / serverless — the implementation-specific coupling flagged when this was opened.

What would unblock these implementations:

- a capability / opt-out letting a Gateway implementation declare its data plane non-probeable, with net-gateway-api falling back to Gateway API status (`Programmed` + matching `observedGeneration`) for readiness — the implementation then owns reporting that honestly; and/or
- if probing stays mandatory, document the in-cluster-reachability requirement explicitly, so a non-probeable data plane is a known-unsupported case rather than a silent permanent `Uninitialized`.

<details>
<summary>Full reproduction (kind · Knative Serving v1.22.1 · net-gateway-api v1.22.1)</summary>

`config-gateway` points at a Gateway backed by the tunnel controller, off-cluster mode (no `service:`, so the probe targets the Gateway status address):

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway
  namespace: knative-serving
data:
  external-gateways: |
    - class: cloudflare-tunnel
      gateway: knative-serving/knative-gateway
      supported-features:
      - HTTPRouteRequestTimeout
  local-gateways: |
    - class: cloudflare-tunnel
      gateway: knative-serving/knative-gateway
      supported-features:
      - HTTPRouteRequestTimeout
```

Deploy any ksvc (e.g. `helloworld-go`). Everything the Gateway API contract exposes is green:

```text
# HTTPRoute (generated by net-gateway-api)
Accepted=True (Accepted)
ResolvedRefs=True (ResolvedRefs)

# Gateway
Accepted=True / Programmed=True
status.addresses: [{type: Hostname, value: <tunnel-id>.cfargotunnel.com}]

# revision pod
helloworld-00001-deployment-...  2/2  Running

# KIngress
NetworkConfigured=True
LoadBalancerReady=Unknown (Uninitialized: Waiting for load balancer to be ready)
Ready=Unknown (Uninitialized)

# ksvc
READY=Unknown  REASON=Uninitialized   # permanently
```

…but the prober can never reach the data plane, on a loop:

```text
Probing of http://helloworld.default.example.com/ failed,
IP: <tunnel-id>.cfargotunnel.com:80, ready: false,
error: dial tcp: lookup <tunnel-id>.cfargotunnel.com on 10.96.0.10:53: no such host
```

The HTTPRoute config itself is fine — weighted `backendRefs`, the `RequestHeaderModifier` filters (including the injected `K-Network-Hash`), and the exact header matches are all accepted and programmed. Only the probe fails.

</details>

<details>
<summary>Working PoC — what it takes to satisfy the probe with this data plane</summary>

Four changes together make the probe pass; each was individually necessary:

1. The data-plane proxy runs in "tunnel mode" where traffic flows in-process from cloudflared and nothing listens in-cluster. I added an in-cluster HTTP listener on the proxy port serving the same L7 handler, alongside the tunnel (both coexist — the edge stays connected).
2. A `Service` whose **first** declared port is the proxy port — net-gateway-api dials the Service's first port, so a multi-port Service with the config-API port first is probed on the wrong port.
3. A `NetworkPolicy` rule allowing the proxy port from the net-gateway-api controller's namespace (the data-plane policy otherwise only allows its config-API port from the controller namespace, so the probe times out).
4. `config-gateway` `service:` pointed at that Service.

With all four, an in-cluster probe returns exactly what the verifier wants:

```text
$ curl -s -D - -o /dev/null \
    -H "Host: helloworld.default.example.com" \
    -H "K-Network-Probe: probe" -H "K-Network-Hash: override" \
    http://<proxy-pod-ip>:8080/
HTTP/1.1 200 OK
K-Network-Hash: 140a84b099e0d1506f815c27abf87326679e7af503c8b4ff6aad367d653fd88d
```

`KIngress` goes `Ready=True`, the ksvc goes `Ready`, and publishing a new revision rolls over cleanly (the proxy then serves the new revision's content). So the `K-Network-Hash` contract itself is fully satisfiable by a non-Envoy data plane — the blocker is purely that the probe must reach an in-cluster HTTP listener, which an off-cluster/tunnel data plane has no reason to expose. This works for me as a workaround, but it isn't something every off-cluster data plane can do.

</details>

Could this be reopened? `/remove-lifecycle stale`
